### ISSUE TITLE
Graphical display interface of Toy Env not found.

### ISSUE THREAD

**Issue by momofive** [ChengshuLi/HRL4IN#3]
Hi, Chengshu, I didn't find any Graphical display interface of Toy Env, is it because it wasn't made public？Thanks！

**Comment by ChengshuLi** [comment]
@Silva-Q Yes it wasn't made public and I actually had a hard time finding that piece of code. It's based on this repo: https://github.com/maximecb/gym-minigrid. I currently don't have the bandwidth to implement this feature but if you want, please feel free to make a pull request and that will be greatly appreciated!!
